openapi: '3.0.3'
info:
  title: transmitter internal API
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Local server
  - url: https://liscitransmitter.live
    description: Production server
paths:
  /:
    get:
      summary: Root endpoint
      responses:
        '200':
          description: API endpoint message
  /login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
        '401':
          description: Invalid Username or Password
  /logout:
    get:
      summary: User logout
      responses:
        '200':
          description: Successful logout
  /checkLogin:
    get:
      summary: Check login status
      responses:
        '200':
          description: Logged in
        '401':
          description: Not logged in
  /uploadFile:
    post:
      summary: Upload a file
      responses:
        '200':
          description: File uploaded successfully
        '401':
          description: Not logged in
        '403':
          description: You cannot upload a file
        '500':
          description: File upload error
  /uploadImage:
    post:
      summary: Upload an image
      responses:
        '200':
          description: Image uploaded successfully
        '401':
          description: Not logged in
        '403':
          description: You cannot upload an image
        '500':
          description: Image upload error
  /createPost:
    post:
      summary: Create a new post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                sections:
                  type: string
                permissions:
                  type: string
      responses:
        '200':
          description: Post created successfully
        '401':
          description: Not logged in
        '403':
          description: You cannot create a post
        '400':
          description: Missing or invalid parameters
        '500':
          description: Error creating post
  /updatePost:
    post:
      summary: Update a post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postID:
                  type: string
                title:
                  type: string
                sections:
                  type: string
                permissions:
                  type: string
      responses:
        '200':
          description: Post updated successfully
        '401':
          description: Not logged in
        '403':
          description: You cannot update a post
        '400':
          description: Missing or invalid parameters
        '500':
          description: Error updating post
  /getPosts:
    get:
      summary: Get posts
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number
      responses:
        '200':
          description: List of posts
  /getPost/{id}:
    get:
      summary: Get a post by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Post ID
      responses:
        '200':
          description: Post details
        '403':
          description: You cannot view this post
        '404':
          description: Post not found
  /deletePost:
    post:
      summary: Delete a post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postID:
                  type: string
      responses:
        '200':
          description: Post deleted successfully
        '401':
          description: Not logged in
        '403':
          description: You cannot delete this post
        '400':
          description: Missing or invalid parameters
  /createCitation:
    post:
      summary: Create a new citation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                author:
                  type: string
                content:
                  type: string
      responses:
        '200':
          description: Citation created successfully
        '401':
          description: Not logged in
        '400':
          description: Missing or invalid parameters
  /getCitations:
    get:
      summary: Get citations
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number
      responses:
        '200':
          description: List of citations
        '401':
          description: Not logged in
        '403':
          description: You cannot get this data
  /deleteCitation:
    post:
      summary: Delete a citation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                citationID:
                  type: string
      responses:
        '200':
          description: Citation deleted successfully
        '401':
          description: Not logged in
        '403':
          description: You cannot delete this citation
        '400':
          description: Missing or invalid parameters
  /updateCitation:
    post:
      summary: Update a citation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                citationID:
                  type: string
                author:
                  type: string
                content:
                  type: string
      responses:
        '200':
          description: Citation updated successfully
        '401':
          description: Not logged in
        '403':
          description: You cannot update this citation
        '400':
          description: Missing or invalid parameters
  /pushSubscribe:
    post:
      summary: Subscribe to push notifications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Subscription successful
        '401':
          description: Not logged in
  /likePost:
    post:
      summary: Like a post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postID:
                  type: string
      responses:
        '200':
          description: Post liked successfully
        '401':
          description: Not logged in
        '400':
          description: Missing or invalid parameters
        '500':
          description: Error liking post
  /createComment:
    post:
      summary: Create a comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postID:
                  type: string
                content:
                  type: string
                permissions:
                  type: string
      responses:
        '200':
          description: Comment created successfully
        '401':
          description: Not logged in
        '400':
          description: Missing or invalid parameters
  /deleteComment:
    post:
      summary: Delete a comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commentID:
                  type: string
      responses:
        '200':
          description: Comment deleted successfully
        '401':
          description: Not logged in
        '403':
          description: You cannot delete this comment
        '400':
          description: Missing or invalid parameters
  /updateComment:
    post:
      summary: Update a comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commentID:
                  type: string
                content:
                  type: string
      responses:
        '200':
          description: Comment updated successfully
        '401':
          description: Not logged in
        '403':
          description: You cannot update this comment
        '400':
          description: Missing or invalid parameters