openapi: '3.0.3'
info:
  title: transmitter internal API
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Local server
  - url: https://liscitransmitter.live
    description: Production server
paths:
  /:
    get:
      summary: Root endpoint
      responses:
        '200':
          description: API endpoint message
  /login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
        '401':
          description: Invalid Username or Password
  /logout:
    get:
      summary: User logout
      responses:
        '200':
          description: Successful logout
  /checkLogin:
    get:
      summary: Check login status
      responses:
        '200':
          description: Logged in
        '401':
          description: Not logged in
  /upload:
    post:
      summary: Upload a file
      responses:
        '200':
          description: File uploaded successfully
        '401':
          description: Not logged in
        '403':
          description: You cannot upload a file
        '500':
          description: File upload error
  /uploadImage:
    post:
      summary: Upload an image
      responses:
        '200':
          description: Image uploaded successfully
        '401':
          description: Not logged in
        '403':
          description: You cannot upload an image
        '500':
          description: Image upload error
  /createPost:
    post:
      summary: Create a new post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                teachersafe:
                  type: boolean
                upload:
                  type: string
      responses:
        '200':
          description: Post created successfully
        '401':
          description: Not logged in
        '403':
          description: You cannot create a post
        '500':
          description: Error creating post
  /getPosts:
    get:
      summary: Get posts
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number
      responses:
        '200':
          description: List of posts